listener {
 timeout = 300
 on-timeout = ~/.config/hypr/scripts/brightness_idle.sh dim
 on-resume = ~/.config/hypr/scripts/brightness_idle.sh restore
}

listener {
 timeout = 900
 on-timeout = ~/.config/hypr/scripts/dpms_then_sleep.sh start 15
 on-resume = ~/.config/hypr/scripts/dpms_then_sleep.sh cancel-and-lock
}

listener {
 timeout = 840
 on-timeout = notify-send "Inactivity detected" "Screen will turn off in 60 seconds!"
 on-resume = notify-send "Activity detected" "Screen off is prevented or lifted!"
}

listener {
 timeout = 2700
 on-timeout = true
}
