listener {
 timeout = 300
 on-timeout = hyprctl dispatch dpms off; hyprlock
 on-resume = hyprctl dispatch dpms on
}
listener {
 timeout = 270
 on-timeout = notify-send "Inactivity detected" "System will be locked in 30 seconds!"
 on-resume = notify-send "Activity detected" "System lock is prevented or lifted!"
}
