# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e6e1e2"

# Title color for boxes
theme[title]="#ccc3d5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cac4cc"

# Background color of selected item in processes box
theme[selected_bg]="#ccc3d5"

# Foreground color of selected item in processes box
theme[selected_fg]="#332e3b"

# Color of inactive/disabled text
theme[inactive_fg]="#cac5cc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ccc7ac"

# Cpu box outline color
theme[cpu_box]="#948f96"

# Memory/disks box outline color
theme[mem_box]="#948f96"

# Net up/down box outline color
theme[net_box]="#948f96"

# Processes box outline color
theme[proc_box]="#948f96"

# Box divider line and small boxes line color
theme[div_line]="#49464b"

# Temperature graph colors
theme[temp_start]="#cac4cc"
theme[temp_mid]="#ccc3d5"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cac4cc"
theme[cpu_mid]="#ccc3d5"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#cac4cc"
theme[free_mid]=""
theme[free_end]="#49454c"

# Mem/Disk cached meter
theme[cached_start]="#ccc7ac"
theme[cached_mid]=""
theme[cached_end]="#2a2816"

# Mem/Disk available meter
theme[available_start]="#ccc3d5"
theme[available_mid]=""
theme[available_end]="#2a2532"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#cac4cc"
theme[download_mid]="#ccc3d5"
theme[download_end]="#ccc7ac"

# Upload graph colors
theme[upload_start]="#cac4cc"
theme[upload_mid]="#ccc3d5"
theme[upload_end]="#ccc7ac"